Add Tekken 7 & 8
Whisky-App/whisky-book pull request #101
Opened 2024-10-01 20:26 UTC by hahayupgit

Unplayable :-(

2024-10-01 23:38 UTC, mattmaniak requested changes

2024-10-01 23:38 UTC, mattmaniak commented on src/game-support/tekken7.md
> +Tekken 7 is currently **unplayable** in Whisky.
Why is it exactly inplayable?

2024-10-01 23:39 UTC, hahayupgit commented on src/game-support/tekken7.md
> +Tekken 7 is currently **unplayable** in Whisky.
Clicking "play game" does nothing

2024-10-02 19:01 UTC, hahayupgit commented
hahaha i was confused at your comment at first, i thought you were directly asking me for an explanation rather than asking me to add those details to the page

2024-10-02 19:37 UTC, mattmaniak commented
Not as deep 🙃

2024-10-02 19:38 UTC, mattmaniak approved these changes

2024-10-02 19:38 UTC, merged