Added support for Against The Storm
Whisky-App/whisky-book pull request #136
Opened 2024-11-25 15:39 UTC by tsainez

# Description
This pull request adds documentation for support for the game "[Against The Storm](https://store.steampowered.com/app/1336490/Against_the_Storm/)." 

## Type(s) 

- [x] Game page addition

## Verification 
Have you

- [x] Followed the [contribution guidelines?](https://github.com/Whisky-App/whisky-book?tab=readme-ov-file#please-read-all-steps-before-contributing)
- [x] Ran `./scripts/generate.mjs`?
- [x] Ran `./scripts/lint.mjs`?
- [x] Checked spelling and grammar?
- [x] (If applicable) Provided documentation for a game not working? (i.e. detailing what happens when the game doesn't work?)
- [x] (If applicable) Ensured the linked Steam ID is the correct one for your game addition?

2024-11-25 16:27 UTC, mattmaniak commented
What's the need of <> signs around the title? I don't see their presence ob Steam page nor when googling the game.

2024-11-25 18:54 UTC, tsainez commented
I'm not sure why, but when I run the generate script the `&lt;` gets added.

2024-11-25 20:13 UTC, mattmaniak requested changes
Please remove the <> signs from the title name and run ./scripts again as there is no point to include such characters in the title.

2024-11-27 10:02 UTC, tsainez commented
I have committed a change that removes the brackets from the text.

2024-11-27 10:38 UTC, mattmaniak commented
It removes brackets only from the Summary.md file. Please do it in the game page and run scripts again.

2025-01-02 20:45 UTC, hahayupgit approved these changes

2025-01-02 21:01 UTC, mattmaniak approved these changes

2025-01-02 21:01 UTC, merged