Adds Ballionaire to the games list
Whisky-App/whisky-book pull request #145
Opened 2024-12-17 00:44 UTC by zaklembarra

# Description

Added Ballionaire. Was excited to play this on Whisky, sadly doesn't work. Fwiw this also doesn't work on vanilla wine, I tested it there too :(

Curious if similar issues are common across Godot games, but couldn't find much online and don't have time to do more digging for now.

## Type(s) 

- [x] Game page addition
- [ ] Game page modification
- [ ] Other wiki edit

## Verification 
Have you

- [x] Followed the [contribution guidelines?](https://github.com/Whisky-App/whisky-book?tab=readme-ov-file#please-read-all-steps-before-contributing)
- [x] Ran `./scripts/generate.mjs`?
- [x] Ran `./scripts/lint.mjs`?
- [x] Checked spelling and grammar?
- [x] (If applicable) Provided documentation for a game not working? (i.e. detailing what happens when the game doesn't work?)
- [x] (If applicable) Ensured the linked Steam ID is the correct one for your game addition?

2024-12-17 09:59 UTC, mattmaniak requested changes

2024-12-17 09:59 UTC, mattmaniak commented on src/game-support/ballionaire.md
> +## Notes
Please mark this as a > [WARNING], including the error logs.

2024-12-17 17:24 UTC, mattmaniak approved these changes

2024-12-17 17:25 UTC, merged

2024-12-19 00:23 UTC, ericpridham commented
@zaklembarra I got it to work by adding "--rendering-driver vulkan" to the launch options in Steam.

2024-12-19 11:19 UTC, mattmaniak commented
> @zaklembarra I got it to work by adding "--rendering-driver vulkan" to the launch options in Steam.

What Status do you propose to set? I mean a quality of the gameplay like we rate this in other games.

2024-12-19 22:04 UTC, ericpridham commented
I was able to play a couple hours without a crash. There is a minor display bug with arrow characters, so probably silver?

2024-12-20 11:44 UTC, mattmaniak commented
Thanks. I Agree with the status. I will update it soon.

2024-12-21 22:22 UTC, mattmaniak commented
Addressed in #149