Add 11 games; fix Quake II name inconsistency
Whisky-App/whisky-book pull request #29
Opened 2024-05-09 17:34 UTC by mattmaniak

Tested on M2 16 GB. Some them work out-of-the-box, some have sound issues, some needs fixes because of launching issues.

2024-05-09 17:43 UTC, hahayupgit requested changes
Looks good, change date formatting to mm-dd-yy (I prefer yy-mm-dd but this is from Isaac). Once these fixes are made and I verify the Steam IDs you should be good to merge.

2024-05-09 17:43 UTC, hahayupgit commented on src/SUMMARY.md
> +  - [Assassin's Creed: Director's Cut Edition](./game-support/ac.md)
Change name to ac-directors-cut

2024-05-09 17:43 UTC, hahayupgit commented on src/SUMMARY.md
> +  - [Call of Cthulhu](./game-support/cthulhu.md)
change name to call-of-cthulhu

2024-05-09 17:43 UTC, hahayupgit commented on src/SUMMARY.md
> +  - [Stronghold Crusader HD](./game-support/stronghold-c-hd.md)
change name to stronghold-crusader-hd

2024-05-09 17:43 UTC, hahayupgit commented on src/SUMMARY.md
> +  - [The Vanishing of Ethan Carter](./game-support/vanishing-of-ethan.md)
change name to vanishing-of-ethan-carter

2024-05-09 17:46 UTC, hahayupgit commented
Also those name changes are just personal suggestion, I wouldn't have any issue with them as they are (except maybe Call of Cthulhu) if the Discord bot didn't rely on file names to search for a game in the Docs.

Side note but I'll probably figure out a better way to handle that as its current implementation isn't great.

2024-05-09 18:01 UTC, mattmaniak commented
Thanks for the feedback. I have fixed all dates of the games I have added as I stick to DD/MM/YY format daily and made it by habit... Names are also updated per suggestion. I think the issue is that acronyms are encouraged in the contributing guide in README.md but there is no detailed case description/example where to acronym and where not.

2024-05-09 18:03 UTC, hahayupgit commented
Of course! And I agree, I'm working on a better way to handle file names rn so it'll be more clarified soon

2024-05-09 18:05 UTC, hahayupgit commented
BTW when you're done just request me for a review and I'll check it out

2024-05-09 18:57 UTC, mattmaniak commented
Also I think that NOTEs and WARNINGs are a loosely defined too. I use to put not-gameplay-breaking info in Notes while anything that affects a gameplay in Warnings. It's my interpretation but I see that it varies from person to person and it may lower readbility.

By requesting you you mean to assign you somehow to PR or just mention? PR is ready in my side tho.

2024-05-10 11:46 UTC, mattmaniak commented
Added 4 more games: Hellblade, Blitzkrieg 2, The Witcher 3, LEGO Clone Wars.

2024-05-11 13:18 UTC, mattmaniak commented
Fallout 3 GOTY added.

2024-05-12 04:00 UTC, IsaacMarovitz approved these changes

2024-05-12 04:00 UTC, merged