Create v-rising.md
Whisky-App/whisky-book pull request #35
Opened 2024-05-13 12:48 UTC by git-st0m

hey, just added a V Rising review on MacBook M3

2024-05-13 13:57 UTC, JoshuaBrest commented
Please fix all lint issues.

2024-05-13 19:35 UTC, JoshuaBrest requested changes

2024-05-13 19:35 UTC, JoshuaBrest commented on src/game-support/v-rising.md
> +V Rising
Add heading
```diff
- V Rising
+ # V Rising
```

2024-05-13 19:35 UTC, JoshuaBrest commented on src/game-support/v-rising.md
> +
Add aliases.
```diff
+ <!-- script:Aliases [] -->
  
```

2024-05-13 19:35 UTC, JoshuaBrest commented on src/game-support/v-rising.md
> +{{#template ../templates/steam.md id=1604030}}
After making the above changes, run `./script/generate.mjs`.

2024-07-11 01:09 UTC, hahayupgit approved these changes

2024-07-11 01:10 UTC, merged