Add Homeworld 3.
Whisky-App/whisky-book pull request #44
Opened 2024-05-18 21:08 UTC by MetaRossi

Add the Steam game Homeworld 3. Works really well. Possibly due to being an Unreal Engine 4 game.

2024-05-19 04:28 UTC, devium335 requested changes
Make sure to add your game to `/src/game-support/README.md`

2024-05-19 04:32 UTC, JoshuaBrest commented
> Make sure to add your game to `/src/game-support/README.md`

Please ignore this comment

2024-05-19 04:34 UTC, JoshuaBrest approved these changes
LGTM ❤️

2024-05-19 04:34 UTC, JoshuaBrest commented on src/game-support/hw-3.md
> +{{#template ../templates/rating.md status=Platinum installs=Yes opens=Yes}}
I prefer a Gold review, but this could be considered platinum.

2024-05-19 04:36 UTC, devium335 approved these changes
My bad I forgot we migrated away from storing the games in that file

2024-05-19 04:36 UTC, JoshuaBrest commented
> My bad I forgot we migrated away from storing the games in that file

All good!!!!! (:

2024-05-20 01:51 UTC, IsaacMarovitz approved these changes

2024-05-20 01:52 UTC, merged