Add 3 games; Precise contributing docs, especially "opens" flag requirements, fix typos
Whisky-App/whisky-book pull request #59
Opened 2024-06-24 15:58 UTC by mattmaniak

My proposal is targeted to clarify the `opens` flag which says whether a game "opens"... The issue I have found with it is that it was not clear if a game that crashes after 1, 5 or 10 seconds can be considered as "opening". Now a requirement to mark a game as "opening" is ability to launch it to it's default screen (the one that is loaded after launch without using any input) which is most often a main menu.

2024-07-04 00:55 UTC, JoshuaBrest requested changes

2024-07-04 00:55 UTC, JoshuaBrest commented on README.md
> +   Ensure that you're replacing the `<>` tags with the proper values in order to comply with the wiki layout. If a game is no longer available on Steam or it is not available there at all then provid
> If a game is no longer available on Steam or it is not available there at all then provide a valid link to the store or to the download page. **Entering pirate, potentially copyright-breaking and non-store executables links is disallowed.** Whisky was created to run regular Windows games without any codebase alteration.

Unnecessary IMO.

2024-07-04 00:55 UTC, JoshuaBrest commented on README.md
> +2. Add the following template to your markdown file. Write whether a game installs without any errors and opens properly according to the parameters in an example below. Set `opens` to `Yes` only if
> Write whether a game installs without any errors and opens properly according to the parameters in an example below. Set `opens` to `Yes` only if a game launches successfully to it's default screen, eg. main menu or initial gameplay if it lacks a main menu. Any crash, freeze or error before this breakpoint means that the game does not open and it should be filled with `opens=No`.

Should be in "Standards to uphold"

2024-07-04 00:55 UTC, JoshuaBrest commented on src/game-support/README.md
> +| Garbage  | Game does not work at all or it is not playable due to in-game issues.                         |
```diff
- | Garbage  | Game does not work at all or it is not playable due to in-game issues.                         |
+ | Garbage  | Game is unplayable or does not work at all.                                                    |
```

Grammar.

2024-07-04 00:55 UTC, JoshuaBrest commented on src/game-support/call-of-cthulhu-dcote.md
>  <!-- script:Aliases [] -->
IDK if you want to do this, but since you're formatting, can you add an alias?
`Call of Cthulhu Dark Corners of the Earth` (without the colon).

2024-07-04 00:55 UTC, JoshuaBrest commented on src/game-support/coj-bound-in-blood.md
>  <!-- script:Aliases [] -->
Can you add an alias here too? `Call of Juarez Bound in Blood`

2024-07-04 00:55 UTC, JoshuaBrest commented on src/game-support/coj-gunslinger.md
>  <!-- script:Aliases [] -->
Can you add an alias here too? `Call of Juarez Gunslinger`

2024-07-04 00:55 UTC, JoshuaBrest commented on src/game-support/hellblade2.md
> +<!-- script:Aliases [] -->
Can you add an alias here too?
- `Senua’s Saga: Hellblade 2`
- `Senua’s Saga Hellblade II`
- `Senua’s Saga Hellblade 2`
- `Senua's Saga: Hellblade II`
- `Senua's Saga: Hellblade 2`
- `Senua's Saga Hellblade II`
- `Senua's Saga Hellblade 2`.

2024-07-04 00:55 UTC, JoshuaBrest commented on src/game-support/lotf-2014.md
>  <!-- script:Aliases [] -->
Can you add an alias here too? `Lords Of The Fallen 2014`.

2024-07-04 00:55 UTC, JoshuaBrest commented on src/game-support/mb-wfas.md
>  <!-- script:Aliases [] -->
Can you add an alias here too?
- `Mount and Blade: With Fire and Sword`
- `Mount & Blade With Fire & Sword`
- `Mount and Blade With Fire and Sword`

2024-07-04 00:55 UTC, JoshuaBrest commented on src/game-support/rtcw.md
>      "RTCW"
This alias should be removed because it is an acronym.

2024-07-04 00:55 UTC, JoshuaBrest commented on src/game-support/splinter-cell.md
> +<!-- script:Aliases [] -->
Can you add `Splinter Cell` as an alias here?

2024-07-04 00:55 UTC, JoshuaBrest commented on README.md
> +    | Silver   | Game requires some configuration to run and/or has minor defects.                              |
It should be a space, not a slash.

2024-07-04 00:55 UTC, JoshuaBrest commented on src/game-support/sw-battlefront2-2005.md
> +{{#template ../templates/rating.md status=Bronze installs=Yes opens=Yes}}
Unless sound is necessary to gameplay, this should be `Silver`.

2024-07-04 00:55 UTC, JoshuaBrest commented on src/game-support/sw-battlefront2-2005.md
>  <!-- script:Aliases [] -->
Aliases:
- `Star Wars: Battlefront 2 (Classic, 2005)`
- `Star Wars: Battlefront II (2005)`
- `Star Wars: Battlefront 2 (2005)`
- `Star Wars: Battlefront II 2005`
- `Star Wars: Battlefront 2 2005`
- `Star Wars Battlefront II (Classic, 2005)`
- `Star Wars Battlefront 2 (Classic, 2005)`
- `Star Wars Battlefront II (2005)`
- `Star Wars Battlefront 2 (2005)`
- `Star Wars Battlefront II 2005`
- `Star Wars Battlefront 2 2005`

2024-07-04 00:55 UTC, JoshuaBrest commented on src/game-support/sniper-gw.md
>  <!-- script:Aliases [] -->
Can you add `Sniper Ghost Warrior` as an alias?

2024-07-05 09:43 UTC, mattmaniak commented
@JoshuaBrest all code review proposals are applied.

2024-07-07 09:40 UTC, mattmaniak commented
Golden Just Cause 2 has been added.

2024-07-07 10:35 UTC, mattmaniak commented
Add Deus Ex: Human Revolution - Director's Cut.

2024-07-07 10:36 UTC, mattmaniak commented
Add Kholat.

2024-07-08 05:10 UTC, JoshuaBrest requested changes

2024-07-08 05:10 UTC, JoshuaBrest commented on README.md
> +   - You can add games that already have a native macOS port. Those ports are sometimes poorly optimized and or full of bugs so it could be better solution to play a Windows version of a game via Whi
This seems unnecessary. We already have games such as Among Us with a "mac port" (technically iPad version).

2024-07-08 05:10 UTC, JoshuaBrest commented on README.md
> +   - Write whether a game installs without any errors and opens properly according to the parameters in an example below. Set `opens` to `Yes` only if a game launches successfully to it's default scr
Change to
```
- Document the installation process and any errors that arise during the installation. If installation fails, set `installs=No` in the `Ratings` template.
- Document whether a program opens by setting `opens=Yes` in the `Ratings` template. A program is considered "open" if it launches the title screen or main menu. Dialog messages don't count as a program "opening".
```

2024-07-08 05:10 UTC, JoshuaBrest commented on README.md
> +    | Garbage  | Game does not work at all or it's playability is quite limited due to the technical issues.    |
What about:
```diff
+ | Garbage  | Game is unplayable.                                                                            |
```

2024-07-08 12:08 UTC, JoshuaBrest approved these changes
LGTM

2024-08-23 13:03 UTC, closed without merging