add Splinter Cell Blacklist page
Whisky-App/whisky-book pull request #62
Opened 2024-07-05 05:06 UTC by kstlouis

2024-07-08 17:11 UTC, mattmaniak approved these changes

2024-07-11 00:39 UTC, hahayupgit requested changes

2024-07-11 00:39 UTC, hahayupgit commented on src/game-support/bioshock-infinite.md
> +<!-- script:Aliases [
These aliases are not required, please delete and change to `<!-- script: Aliases [] -->`

2024-07-11 00:39 UTC, hahayupgit commented on src/game-support/tcscb.md
> +<!-- script:Aliases [
Same as above

2024-07-11 00:46 UTC, hahayupgit approved these changes

2024-07-11 00:46 UTC, merged