Add Shadow of the Tomb Raider: DE as Supported.
Whisky-App/whisky-book pull request #65
Opened 2024-07-23 16:21 UTC by lucsoft

Tested with v2.3.2

2024-07-24 10:36 UTC, mattmaniak requested changes
Please regenerate a src/SUMMARY.md with the game title entry.

2024-07-26 09:51 UTC, mattmaniak requested changes

2024-07-26 09:51 UTC, mattmaniak commented on src/game-support/shadow-of-the-tomb-raider-de.md
> +<!-- script:Aliases [] -->
Add an alias:
```
<!-- script:Aliases [
    "Shadow of the Tomb Raider Definitive Edition"
] -->
```

2024-07-26 09:51 UTC, mattmaniak commented on src/game-support/shadow-of-the-tomb-raider-de.md
> +- Download in Heroic as normal, select whisky and set the custom environment variables.
Please add this below line to link a Steam page of the game:
```
{{#template ../templates/steam.md id= 750920}}
```

2024-07-26 13:09 UTC, mattmaniak approved these changes
Looks ok. Thanks.

2024-08-23 03:15 UTC, hahayupgit approved these changes

2024-08-23 03:18 UTC, merged