Added Kebab Chefs!
Whisky-App/whisky-book pull request #68
Opened 2024-07-27 10:34 UTC by axoking

I added game support for Kebab Chefs

I tested it on my M1 Mac

suiii

2024-07-27 10:44 UTC, mattmaniak requested changes
I would recommend to degrade the game from Silver to Bronze due to the serious performance issues and a need to restart a Mac in order to play it. I limits playability a lot.

2024-07-28 07:07 UTC, mattmaniak approved these changes
It is fine now.

2024-08-23 02:30 UTC, hahayupgit approved these changes

2024-08-23 02:30 UTC, hahayupgit commented
In the future, things like `- You might need to restart the game / your PC a few times to play` can be added as a note, similarly to the `[!WARNING]` below it.

2024-08-23 02:31 UTC, merged