Added 2 games
Whisky-App/whisky-book pull request #72
Opened 2024-08-12 03:18 UTC by thunder-blight

Added sf6.md and gbfvs.md including setups

2024-08-12 09:11 UTC, mattmaniak requested changes
Please add those games to SUMMARY.md as mentioned in Readme.

2024-08-12 10:22 UTC, thunder-blight commented
Hey I added them both, can you please review it and let me know?

2024-08-12 12:52 UTC, mattmaniak approved these changes
Looks good now.

2024-08-22 13:29 UTC, hahayupgit approved these changes

2024-08-22 15:02 UTC, merged