Added 1 Games
Whisky-App/whisky-book pull request #75
Opened 2024-08-13 09:06 UTC by plyght

Added game: ZERO Sievert

2024-08-13 09:24 UTC, mattmaniak requested changes

2024-08-13 09:24 UTC, mattmaniak commented on src/game-support/zero-sievert.md
> +
Remove redundant whitespace.

2024-08-22 13:26 UTC, hahayupgit requested changes

2024-08-22 13:26 UTC, hahayupgit commented on src/game-support/zero-sievert.md
> +{{#template ../templates/steam.md id=1782120q}}
Remove the `q` at the end of the Steam ID

2024-08-22 18:33 UTC, hahayupgit approved these changes

2024-08-22 18:33 UTC, merged