Calisto Protocal, MW2, and RE4
Whisky-App/whisky-book pull request #79
Opened 2024-08-25 14:41 UTC by joshandersn

2024-08-25 17:02 UTC, mattmaniak requested changes

2024-08-25 17:02 UTC, mattmaniak commented on src/game-support/calisto-protocal.md
> +# The Calisto Protocal
Typo. Please insert "Protocol" instead of "Protocal".

2024-08-25 17:02 UTC, mattmaniak commented on src/game-support/calisto-protocal.md
> +    "Calisto Protocal"
Typo. Please insert "Protocol" instead of "Protocal".

2024-08-26 08:12 UTC, mattmaniak approved these changes

2024-08-28 19:14 UTC, mattmaniak approved these changes

2024-08-28 19:14 UTC, mattmaniak approved these changes

2024-09-01 15:42 UTC, joshandersn commented
Added two more games to this pull FYI

2024-09-11 05:43 UTC, mattmaniak approved these changes

2024-09-12 08:05 UTC, mattmaniak approved these changes

2024-09-22 11:45 UTC, merged