Game Support: Add GTA IV
Whisky-App/whisky-book pull request #91
Opened 2024-09-20 23:22 UTC by felix-schindler

unplayable

2024-09-21 17:07 UTC, mattmaniak requested changes
Please run the "generate" script to add the game to games list.

2024-09-22 20:52 UTC, mattmaniak commented on src/game-support/gta-4.md
> +Crashes during load without error message and is therefore currently unplayable in Whisky.
Does the game crashes itself or the Rockstar Launcher?

2024-09-22 21:15 UTC, mattmaniak commented on src/game-support/gta-4.md
> +Crashes during load without error message and is therefore currently unplayable in Whisky.
Additionally please add Steam ID of GTA IV as it may be helpful for others to locate this game on Steam.

2024-10-09 10:55 UTC, felix-schindler commented
superseded by #105

2024-10-09 10:55 UTC, closed without merging